parameters:
    # entities
    disjfa_demo.customer.entity.class: Disjfa\DemoBundle\Entity\Customer


services:
  disjfa_demo.provider.demo_channel_type:
    class: Disjfa\DemoBundle\Provider\DemoChannelType
    tags:
      - { name: oro_integration.channel, type: disjfa_demo }

  disjfa_demo.provider.rest_transport:
    class: Disjfa\DemoBundle\Provider\RestTransport
    parent: oro_integration.transport.rest.abstract_transport
    tags:
      - { name: oro_integration.transport, type: rest, channel_type: disjfa_demo }
